env:
  build_version: "5.4"
  flutter_version: "3.10.1"

name: Android build version 5.4
on:
  push:
    tags:
      - "*"
  #   branches: [build-app]
  # pull_request:
  #   branches: [build-app]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          version: ${{ env.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      # - name: Run tests
      #   run: flutter test

      - name: Build apk app
        run: flutter build apk

      - name: Archive android artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ secrets.APP_NAME }}
          path: build/app/outputs/flutter-apk/app-release.apk

      # - name: Fastlane Setup
      #   run: gem install bundler && bundle install --gemfile=fastlane/Gemfile

      # - name: Update App Version
      #   run: bundle exec fastlane update_version version_number:"1.0.1"

      - name: Deploy android to firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: "internal-testers"
          releaseNotes: "Test build ${{ env.build_version }}"
          file: "build/app/outputs/flutter-apk/app-release.apk"
