name: Builds V2.7
on:
  push:
    tags:
      - "*"
  #   branches: [build-app]
  # pull_request:
  #   branches: [build-app]

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.1"
      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos/
# jobs:
#   build:
#     name: Build ${{ matrix.target }}
#     runs-on: macos-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         target:
#           ["apk --debug", "ios --no-codesign"]
#           # ["apk --debug", "appbundle --debug", "ios --no-codesign", macos, web]
#     steps:
#       - name: Set up JDK 11
#         uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
#         with:
#           java-version: 11
#           distribution: temurin

#       # Set up Flutter.
#       - name: Clone Flutter repository with master channel
#         uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
#         with:
#           channel: master
#       - run: flutter config --enable-macos-desktop
#       - run: flutter doctor -v

#       # Checkout gallery code and get packages.
#       - name: Checkout gallery code
#         uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
#       - run: flutter pub get
#       - run: flutter build ${{ matrix.target }}
