defaults:
  version: 3.6
  flutterVersion: 3.10.1

name: IOS build version $(version)
on:
  push:
    tags:
      - "*"
  #   branches: [build-app]
  # pull_request:
  #   branches: [build-app]

permissions: read-all

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "$(flutterVersion)"

      - name: Install dependencies
        run: flutter pub get

      # - name: Analyze project source
      #   run: dart analyze

      # - name: Run tests
      #   run: flutter test

      - name: Build ios app
        run: flutter build ios --release --no-codesign

      - name: Archive ios artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ secrets.APP_NAME }}
          path: build/ios/iphoneos/

      # - name: Fastlane Setup
      #   run: gem install bundler && bundle install --gemfile=fastlane/Gemfile

      # - name: Update App Version
      #   run: bundle exec fastlane update_version version_number:"1.0.1"

      - name: Deploy ios to firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: "internal-testers"
          releaseNotes: "Test build version $(version)"
          file: "build/ios/iphoneos/Runner.app"
